### ISSUE TITLE
xin file dữ liệu training

### ISSUE THREAD

**Issue by cuonglv0688** [chiakiphan/dl_project#1]
Mình cũng đang muốn tìm hiểu PhoBERT nên thấy project khá hay. Bạn có thể cho mình xin file ner_products_bio.csv của bạn được không?

**Comment by chiakiphan** [comment]
Đây bạn, có 2 điểm bạn nên lưu ý:
1. data mình label còn thiếu cái k chính xác đc 100%, bạn có thể review để
fix lại
2. nếu được bạn có thể đừng public data này giúp mình

Vào Th 6, 22 thg 5, 2020 vào lúc 09:15 cuonglv0688 <
notifications@github.com> đã viết:

**Comment by cuonglv0688** [comment]
Mình không thấy file đính kèm :(
Nếu không public được thì bạn cho mình xin file chứa 1 vài câu ví dụ cũng được. Để mình xem cấu trúc data nhằm chạy code xem thực tế thế nào.

**Comment by chiakiphan** [comment]
Mình gửi lại cho bạn đấy, data m có 3 cột số TT, từ, nhãn, m có visual nó
trong project của m rồi đó
Vào 21:45, CN, 24 Th5, 2020 cuonglv0688 <notifications@github.com> đã viết:

**Comment by cuonglv0688** [comment]
cám ơn bạn nhé.
